version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket testpipelinegithubqm --output-template-file outputemplate.yml
artifacts:
  files:
    - template.yml
    - outputtemplate.yml

