AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library
Resources:
  A3lf2ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: vs
      OpenApiVersion: "2.0"
      DefinitionUri: search_apigateway.yaml
  Frontlexlf:
    Type: AWS::Serverless::Function
    Properties:
      Handler: front2lex.lambda_handler
      Runtime: python3.8
      FunctionName: Frontlexlf
      CodeUri: ./src/front2lex #Directory the source file is
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::840723909099:role/service-role/front_lex-role-odw9js2u
      Policies:
        - AmazonS3FullAccess
        - AlexaForBusinessFullAccess
        - AmazonLexFullAccess
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: A3lf2ApiGateway
      Environment:
        Variables:
          REGION: us-east-1
  Searchlf:
    Type: AWS::Serverless::Function
    Properties:
      Handler: search_photos.lambda_handler
      Runtime: python3.8
      FunctionName: Searchlf
      CodeUri: ./src/search_photos #Directory the source file is
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::840723909099:role/service-role/search-photos-role-1k677fab
      Policies:
        - AWSLambdaBasicExecutionRole-a49340ea-df22-4378-ad40-0127997c95f2
      Environment:
        Variables:
          REGION: us-east-1
  Indexlf:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index_photos.lambda_handler
      Runtime: python3.8
      FunctionName: Indexlf
      CodeUri: ./src/index_photos
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::840723909099:role/service-role/photoIndex-role-sz2l5aln'
      Policies:
        - AWSLambdaBasicExecutionRole-a49340ea-df22-4378-ad40-0127997c95f2
        - AmazonS3FullAccess
      Environment:
        Variables:
          REGION: us-east-1
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e2f229a0-3a9e-4189-8001-8abba8f64885
    DependsOn:
      - ED4G9IJ
  # ED4G9IJ:
  #   Type: 'AWS::Elasticsearch::Domain'
  #   Metadata:
  #     'AWS::CloudFormation::Designer':
  #       id: 89c42226-fd68-42e3-93df-1513b1ce6558
  # photo:
  #   Type: 'AWS::S3::Bucket'
  #   Properties:
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: false
  #       BlockPublicPolicy: false
  #       IgnorePublicAcls: false
  #       RestrictPublicBuckets: false
  #   Metadata:
  #     'AWS::CloudFormation::Designer':
  #       id: d939f2ee-9476-451a-a0a6-9aa7872b1947
  #   DependsOn:
  #     - Indexlf
  # S3BN9ZR:
  #   Type: 'AWS::S3::Bucket'
  #   Properties: {}
  #   Metadata:
  #     'AWS::CloudFormation::Designer':
  #       id: 7f9d2521-d19a-4412-bb2b-c1193420bdb6
  #   DependsOn:
  #     - MyAPI
  