AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library
Resources:
 SampleFunction:
  Type: AWS::Serverless::Function
  Properties:
   Handler: front2lex.lambda_handler
   Runtime: python3.8
   FunctionName: SampleFunction
   CodeUri: ./src/front2lex.py #Directory the source file is
   MemorySize: 128
   Timeout: 30
   Role: arn:aws:iam::840723909099:role/service-role/front_lex-role-odw9js2u
   Policies:
    - AmazonS3FullAccess
    - AlexaForBusinessFullAccess
    - AmazonLexFullAccess
   Environment:
    Variables:
      REGION: us-east-1
  